spring:
  logging:
    level:
      ua:
        edu:
          ukma:
            kataskin:
              smarthomeproject: DEBUG
      root: INFO
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
smarthome:
  templates:
    enabled: true