spring:
  datasource:
    url: jdbc:h2:mem:smarthome;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql.init.mode: always
  jpa.defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2            # http://localhost:8080/h2
  logging:
    level:
      ua:
        edu:
          ukma:
            kataskin:
              smarthomeproject: DEBUG
      root: INFO
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
